PaTiSharedPanel = PaTiSharedPanel or {}
function PaTiSharedPanel.Attach(frame, titleText, contentFrames, settingsText)
    frame:SetBackdrop({ bgFile="Interface\\DialogFrame\\UI-DialogBox-Background", edgeFile="Interface\\Tooltips\\UI-Tooltip-Border", edgeSize=14, insets={left=3,right=3,top=3,bottom=3} })
    frame:SetBackdropColor(0.12,0.10,0.08,0.95)
    frame:SetBackdropBorderColor(0.65,0.58,0.42,1)
    local title=frame:CreateFontString(nil,"OVERLAY","GameFontNormalSmall")
    title:SetPoint("TOPLEFT",frame,"TOPLEFT",16,-11)
    title:SetText(titleText)
    local close=CreateFrame("Button",nil,frame,"UIPanelCloseButton")
    close:SetSize(24,24); close:SetPoint("TOPRIGHT",-2,-2); close:SetScript("OnClick",function() frame:Hide() end)
    local gear=CreateFrame("Button",nil,frame)
    gear:SetSize(24,24); gear:SetPoint("RIGHT",close,"LEFT",-3,0)
    local icon=gear:CreateTexture(nil,"ARTWORK"); icon:SetAllPoints(); icon:SetTexture("Interface\\Buttons\\UI-OptionsButton")
    local chevron=CreateFrame("Button",nil,frame,"UIPanelButtonTemplate")
    chevron:SetSize(24,24); chevron:SetPoint("RIGHT",gear,"LEFT",-3,0); chevron:SetText("⌄")
    local settings=CreateFrame("Frame",nil,UIParent,"BackdropTemplate")
    settings:SetSize(300,100); settings:SetPoint("CENTER",UIParent,"CENTER"); settings:SetFrameStrata("DIALOG")
    settings:SetBackdrop({bgFile="Interface\\DialogFrame\\UI-DialogBox-Background",edgeFile="Interface\\Tooltips\\UI-Tooltip-Border",edgeSize=14,insets={left=3,right=3,top=3,bottom=3}});settings:SetBackdropColor(0.12,0.10,0.08,0.98);settings:SetBackdropBorderColor(0.65,0.58,0.42,1);settings:Hide()
    local st=settings:CreateFontString(nil,"OVERLAY","GameFontNormal");st:SetPoint("TOPLEFT",14,-12);st:SetText(titleText.." – Einstellungen")
    local sb=settings:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");sb:SetPoint("TOPLEFT",14,-40);sb:SetWidth(260);sb:SetJustifyH("LEFT");sb:SetText(settingsText)
    local sx=CreateFrame("Button",nil,settings,"UIPanelCloseButton");sx:SetSize(24,24);sx:SetPoint("TOPRIGHT",-2,-2);sx:SetScript("OnClick",function()settings:Hide()end)
    gear:SetScript("OnClick",function()settings:SetShown(not settings:IsShown())end)
    local collapsed=false
    chevron:SetScript("OnClick",function()collapsed=not collapsed;chevron:SetText(collapsed and "›" or "⌄");for _,item in ipairs(contentFrames)do item:SetShown(not collapsed)end end)
end